### ISSUE TITLE
ドネート調整

### ISSUE THREAD

**Issue by in-the-box** [pixelgram/hot-coins#24]
ウォレットアドレス差し替え

**Comment by masakisaaan** [comment]
Bitcoin : 15zgM5pGHptNE1YP31GQWLKaXixYPcCCGi
Ethereum : 0x1014fc3db00fefc8c6c49029b040b08960a62c01
XEM: NAGJG3-QFWYZ3-7LMI7I-QPSGQN-YADGSJ-ZGJRD2-DIYA
